// src/moteur/extensions/courriels/ecrans/textes.en.ts - the English catalogue of the Emails extension, same shape as textes.fr.ts, served when the back office speaks English.
//
// Le type vient du catalogue francais : une cle oubliee ici casse `pnpm check`.
import type { Textes } from "./textes.fr.ts";

const count = (n: number) => new Intl.NumberFormat("en-GB").format(n);

export const EN: Textes = {
  locale: "en-GB",
  pages: { tableau: "Emails", journal: "Email log", brancher: "Connect emails", reglages: "Email settings" },

  origines: { contact: "Contact form", lettre: "Newsletter", commande: "Order", accuse: "Acknowledgement", essai: "Test", systeme: "Back office (sign-in, invitation)", autre: "Other extension" },
  etats: { envoye: "Sent", refuse: "Refused", plafonne: "Blocked by a limit" },
  originesCourtes: { contact: "Contact", lettre: "Newsletter", commande: "Order", accuse: "Acknowledgement", essai: "Test", systeme: "Back office", autre: "Other" },
  etatsCourts: { envoye: "Sent", refuse: "Refused", plafonne: "Blocked" },
  jamais: "Never",
  sansBase: "The site's database cannot be found: emails can neither be read nor set up. Is the site running with its engine on?",
  panne: (detail: string) => `This screen could not load (${detail}). Reload the page; if it happens again, pass this message on to whoever manages the site.`,
  actualiser: "Refresh",

  tableau: {
    intro: "Every email your site sends (contact form, acknowledgement, test) goes out through Cloudflare and is logged here: what leaves, what fails, and where you stand against this month's allowance.",
    pret: (to: string) => `Everything is connected: contact form messages reach ${to}.`,
    pretTitre: "Emails are going out",
    incompletTitre: "Emails are not connected yet",
    incomplet: (missing: string[]) => `Missing: ${missing.join("; ")}. Until this is done, the contact form looks as before and sends nothing. Open "Connect emails" in the menu: every step is explained there.`,
    manques: {
      liaison: "the site connected to Cloudflare's sending service (Connect emails, step 3)",
      fournisseur: "handing the emails to Emails (Connect emails, step 3, one click)",
      expediteur: "the sender address (Email settings)",
      destinataire: "the recipient of the contact form (Email settings)",
    },
    envoyes: "Sent this month",
    surInclus: (included: number) => `out of ${count(included)} included by Cloudflare`,
    echecs: "Failures this month",
    echecsDetail: (n: number, blocked: number) => (n + blocked === 0 ? "none, everything went out" : `${count(n)} refused, ${count(blocked)} blocked: review them in the log`),
    dernier: "Last email",
    branchement: "Connection",
    branchementPret: "Ready",
    branchementIncomplet: "Incomplete",
    branchementDetail: (binding: boolean) => (binding ? "Sending service connected" : "Sending service not connected yet"),
    jauge: (sent: number, included: number) => `This month's allowance: ${count(sent)} of ${count(included)} included emails`,
    pourcent: (p: number) => `${new Intl.NumberFormat("en-GB", { maximumFractionDigits: 1 }).format(p)}%`,
    cycle: (end: string) =>
      `The counter goes back to zero on ${end}. 3,000 emails a month are included in your hosting plan (shared between your sites if you have several); beyond that, each thousand emails costs about 0.35 US dollars (price read on 16 September 2026).`,
    depasse: (over: number, dollars: string) => `This site went ${count(over)} emails over the allowance: about ${dollars} US dollars more this month if it is alone on the plan.`,
    plafonnesTitre: "Some emails were blocked by your limits",
    plafonnes: (n: number) => `${count(n)} email${n > 1 ? "s" : ""} blocked this month. Nothing is lost: each message is kept in the log, with a "Send again" button. If it was a real visitor, raise the limit in Email settings.`,
    derniers: "Latest emails",
    vide: "No email sent yet. The first contact form message will appear here.",
    carte: (when: string, state: string) => `Last email: ${when}. ${state}.`,
    echecsTitre: (n: number) => (n > 1 ? `${count(n)} emails did not go out` : "An email did not go out"),
    echecCommande:
      'An order email did not go out: your customer may not have received their confirmation. Open "Email log", read the reason next to the email, fix what it says, then click "Send this email again".',
    echecAutre: 'Open "Email log": the reason is written next to each email, with what to do, and a "Send this email again" button.',
  },

  colonnes: { quand: "When", formulaire: "Form", destinataire: "Recipient", sujet: "Subject", etat: "Status", motif: "Why" },

  journal: {
    intro: 'Every email, newest first. Addresses are masked. Pick one in "Open an email" to read the details, understand an error and send it again.',
    filtreEtat: "Status",
    filtreFormulaire: "Form",
    tous: "All",
    plus: "Show 25 more",
    vide: "No email matches this filter.",
    voir: "Open an email",
    choisir: "Pick an email",
    detail: "Email details",
    fournisseur: (who: string) => `Sent through ${who}.`,
    identifiant: (number: string) => `Cloudflare message number, for their support if needed: ${number}`,
    renvoiDe: (when: string) => `Resend of an email from ${when}.`,
    quoiFaire: "What to do",
    contenu: "Email content",
    renvoyer: "Send this email again",
    confirmerTitre: "Send this email again?",
    confirmer: (to: string) => `The same email goes out again to ${to}. It counts against your limits and this month's allowance.`,
    oui: "Send again",
    non: "Cancel",
    renvoye: "The email went out again.",
    renvoiEchec: "It did not go out: the details say why.",
    introuvable: "This email is no longer in the log (it is kept for a little over a year).",
    sansContenu: "This email has no stored content: it cannot be sent again.",
  },

  brancher: {
    intro: "Four steps, done once. Each one says whether it is done. Steps 2 and 3 belong to the person who installed the site: if that is not you, send them this page, everything they need is written there.",
    fait: "Done",
    domaineExemple: "your-domain.com",
    aFaire: "To do",
    etape1: "Step 1: the sender address",
    etape1Ok: (address: string, domain: string) => `Your emails leave from ${address}. The sending domain is therefore ${domain}.`,
    etape1Ko: "No sender address is set. Open \"Email settings\" and enter an address on your own domain (for example hello@your-domain.com). That domain must be managed by Cloudflare.",
    etape2: "Step 2: the domain registered with Cloudflare",
    etape2Texte: (domain: string) =>
      `Cloudflare only sends from a domain name it knows. ${domain} is registered once; Cloudflare then sets the four technical records of the table below itself, and their state is read here.`,
    etape2Consigne: "Cloudflare dashboard, account on the Workers Paid plan: Compute, Email Service, Email Sending, then \"Onboard Domain\". Or, in a terminal:",
    dnsTitre: "Expected DNS records",
    dnsColonnes: { type: "Type", nom: "Name", attendu: "Expected value", lu: "Found", etat: "Status" },
    dnsEtats: { ok: "Good", absent: "Missing", faux: "Different", double: "Duplicated", injoignable: "Not checked" },
    dnsNoms: { mx: "Bounce return", spf: "SPF (lets Cloudflare send)", dkim: "DKIM (signs the emails)", dmarc: "DMARC (one per domain)" },
    dnsOk: "All four records are in place.",
    dnsKo: 'One or more records are missing or different. Right after registering, allow 5 to 15 minutes, then click "Check again".',
    dnsDouble: "Careful: a name carries two SPF records, or the domain carries two DMARC records. Delete the duplicate in Cloudflare, DNS, Records: two records contradict each other and mailboxes keep the worst.",
    dnsInjoignable: "The check could not reach Cloudflare's DNS service. Try again in a moment.",
    dnsVerifie: (time: string) => `Checked with a DNS over HTTPS query to cloudflare-dns.com, on ${time}.`,
    dnsSansDomaine: "Set the sender address first (step 1): its domain is what gets checked.",
    verifier: "Check again",
    etape3: "Step 3: the site connected to the sending service",
    etape3Ok: "The site is connected to Cloudflare's sending service: it can hand its emails to Cloudflare.",
    etape3Ko: "The site is not yet connected to Cloudflare's sending service. The person who installed the site adds one line and puts the site online again: send them this page. Until then, the contact form stays as it was and sends nothing.",
    installateur: "For the person who installed the site",
    etape3Ligne: (name: string, file: string) => `${name} binding, to add to ${file}:`,
    etape3Deployer: "Then, from the site's folder:",
    livreurOk: "Every email of the site goes out this way, the back office's own included.",
    livreurAutre: (who: string) => `The site's emails are handed to ${who}, not to Cloudflare: they do not really go out. Click below to hand them to Emails.`,
    livreurAucun: "No email provider is chosen: nothing can go out. Click below to hand the emails to Emails.",
    livreurPourquoi:
      "Why this choice: online, Emails is the only provider and is chosen on its own. On the computer of the person who installed the site, EmDash adds a test console that writes the emails to its log without sending them: that is the choice to make, once.",
    choisir: "Hand the emails to Emails",
    choisiOk: "Done: Emails now delivers every email of the site.",
    choisiKo: "The choice could not be saved. Reload the page and try again.",
    console: "the development console",
    etape4: "Step 4: the test",
    etape4Texte: (to: string) => `A test email goes to ${to}, your account's address. It takes the same path as the contact form and is logged.`,
    etape4SansAdresse: "Your account has no address: the test has nobody to write to.",
    essai: "Send me a test email",
    essaiOk: (to: string) => `The test email went to ${to}. Check your inbox (and the spam folder, the first time).`,
    essaiKo: "The test email did not go out.",
  },

  reglages: {
    intro: "What you set here applies at once to the site's contact form, with nothing to republish. Each field says what it changes.",
    expediteur: "Sender address: the one people see when they receive your emails. It must be on your own domain (example: hello@your-domain.com).",
    nom: "Name shown next to the address (your company name, for example)",
    reponse: "Reply-to address, optional: where a reply to an acknowledgement lands. Empty: the sender address.",
    destinataire: {
      contact: "Who receives contact form messages (up to three addresses, separated by commas)",
      lettre: "Who is told about a newsletter sign-up",
      commande: "Who is told about a new order",
    },
    accuse: "Send the visitor an acknowledgement",
    accuseAide: "A short confirmation email goes to the person who wrote to you, in their language. It does not repeat their message, so a robot cannot use it to write to someone else in your name.",
    accuseSujet: { fr: "Acknowledgement subject in French", en: "Acknowledgement subject in English" },
    accuseTexte: {
      fr: "Acknowledgement text in French ({nom} becomes the visitor's name, {site} your display name)",
      en: "Acknowledgement text in English ({nom} becomes the visitor's name, {site} your display name)",
    },
    heure: "At most this many emails per hour, all forms together (0: no limit)",
    jour: "At most this many emails per day (0: no limit)",
    parDestinataire: "At most this many emails to one address per day: stops a robot from flooding someone with acknowledgements (0: no limit)",
    mois: "At most this many emails per month: 3,000 are included in the hosting, beyond that they are billed (0: no limit)",
    cycle: "Day of the month when the counter goes back to zero: the day of your Cloudflare invoice (1 to 28)",
    enregistrer: "Save settings",
    annuler: "Discard changes",
    enregistre: "Settings saved: they apply right now.",
    refuse: "Nothing was saved. Fix the following, then save again:",
    refuseBref: "Nothing was saved: the red banner says what to fix.",
    erreurs: {
      expediteur: "the sender address is not a valid address (example: hello@your-domain.com)",
      messagerie:
        "the sender address belongs to a mailbox provider (Gmail, Outlook, Yahoo...): a site cannot send on its behalf. Choose an address on your own domain, for example hello@your-domain.com (the one that ends like your site's address).",
      reponse: "the reply-to address is not a valid address",
      adresse: (form: string) => `an address of "${form}" is not valid`,
      trop: (form: string) => `"${form}" has more than three addresses`,
      plafonds: "a limit is not a whole number between 0 and 100,000",
      cycle: "the cycle day must be a number between 1 and 28",
    },
    apercu: "Acknowledgement preview (what a visitor named Camille would read)",
    apercuVisiteur: "Camille",
    derniere: (when: string, who: string) => `Last changed on ${when} by ${who}.`,
  },

  erreurs: {
    SANS_LIAISON: 'The site is not yet connected to Cloudflare\'s sending service. Open "Connect emails" and follow step 3.',
    SANS_EXPEDITEUR: 'No sender address is set. Enter one in "Email settings".',
    SANS_DESTINATAIRE: 'This form has no recipient. Enter one in "Email settings".',
    SANS_FOURNISSEUR: 'No email provider is chosen. Open "Connect emails", step 3, click "Hand the emails to Emails", then send again.',
    CANAL: 'The email was stopped before it left. Send it again; if it keeps happening, open "Connect emails".',
    E_SENDER_NOT_VERIFIED: 'Cloudflare has not verified the sender domain yet. Open "Connect emails": a DNS record is missing or not propagated yet (allow 5 to 15 minutes). Then send again.',
    E_SENDER_DOMAIN_NOT_AVAILABLE: 'The sender domain is not registered with Cloudflare Email Sending. Follow step 2 of "Connect emails", then send again.',
    E_RECIPIENT_NOT_ALLOWED: "The site's sending service only accepts some addresses, and this one is not among them. Pass this message to the person who installed the site, then send again.",
    E_RECIPIENT_SUPPRESSED: "This address is on Cloudflare's block list (an earlier email bounced or was reported). Check the address; to unblock it: Cloudflare dashboard, Email Service, Suppressions.",
    E_RATE_LIMIT_EXCEEDED: "Cloudflare asks to slow down. Wait a minute, then send again.",
    E_DAILY_LIMIT_EXCEEDED: "The Cloudflare account's daily quota is reached (a new account starts low, then grows on its own). Send again tomorrow, or ask Cloudflare for more.",
    E_DELIVERY_FAILED: "The recipient's server refused the email. Check the address, then send again.",
    E_VALIDATION_ERROR: 'Cloudflare finds the email malformed: an address is probably not valid. Check the addresses in "Email settings".',
    E_FIELD_MISSING: 'A recipient, sender or subject is missing. Check "Email settings".',
    E_CONTENT_TOO_LARGE: "The email is larger than Cloudflare allows (5 MB).",
    E_INTERNAL_SERVER_ERROR: "Cloudflare is briefly unavailable. Send again in a few minutes.",
    plafond: (which, limit) => {
      const window = { heure: "hourly", jour: "daily", destinataire: "per-recipient", mois: "monthly" }[which];
      return `The ${window} limit is reached (${count(limit)} email${limit > 1 ? "s" : ""}). The message is kept here: send it again later, or raise the limit in "Email settings".`;
    },
    inconnue: (code: string, detail: string) => `Cloudflare refused the email (${code}${detail ? `: ${detail}` : ""}). Send again later; if it keeps happening, open "Connect emails".`,
  },

  visiteur: {
    envoye: "Thank you, your message is on its way. We will answer as soon as we can.",
    garde: "Your message could not go out right away. It is kept on our side and we will read it as soon as possible; you can also write to us directly.",
    invalide: "Something is missing: check your name, your address and your message, then send again.",
  },

  courriels: {
    notificationSujet: (subject: string) => `New message from the site: ${subject}`,
    notification: (c) =>
      `New message received through the contact form of ${c.site}.\n\nName: ${c.nom}\nAddress: ${c.adresse}\nSubject: ${c.sujet}\n\n${c.message}\n\nTo answer, simply reply to this email: the reply goes to ${c.adresse}.`,
    sansSujet: "(no subject)",
    essaiSujet: (site: string) => `Test email from ${site}`,
    essai: (site: string, when: string) => `If you are reading this, emails from ${site} go out through Cloudflare.\n\nSent from the back office on ${when}. This test is recorded in the email log.`,
  },
};
